# Generated by Django 4.1.3 on 2022-11-17 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('measurement_date', models.DateField(default=datetime.date(2022, 11, 17))),
                ('measurement_time', models.TimeField(default=datetime.time)),
                ('temperature', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
