# Generated by Django 4.1.3 on 2022-11-18 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CO2_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2sensors',
            name='measurement_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
